### PR TITLE
Updated Readme Docs, updated itemType controller

### PR DESCRIPTION
**Pull request by KerstingJ**

### CODE REVIEW

**Review by AWSafran — COMMENTED** [review]
Did you adjust ResourceServerConfig for the new users mapping? And make sure everyone is aware of the change?

**Review by dgbailey — APPROVED** [review]
Sweet documentation. Leave some fo ME!

**Comment by KerstingJ** [comment]
> Did you adjust ResourceServerConfig for the new users mapping? And make sure everyone is aware of the change?

Yeah the config was set up previously for auth so we thought it was working previously. Now that we have the proper mappings It will actually work.

**Comment by AWSafran** [comment]
> > Did you adjust ResourceServerConfig for the new users mapping? And make sure everyone is aware of the change?
> 
> Yeah the config was set up previously for auth so we thought it was working previously. Now that we have the proper mappings It will actually work.

Sounds good

**Review by AWSafran — APPROVED** [review]

**Pull request merged**
